### PR TITLE
Adds additional boards: Gualtherius LoRaHam

### PR DESCRIPTION
**Pull request by fkaup**
More information:
https://gualtherius.de/product_info.php?products_id=8

### CODE REVIEW

**Comment by peterus** [comment]
@fkaup please update your merge request, there was already a change in the board file.

**Comment by fkaup** [comment]
merge conflict resolved

**Comment by peterus** [comment]
I have two questions:
1. using gpio pins for vcc and gnd is not a good way to deliver power to a display. because a gpio pin can never give the power to a display.
2. why do you set the vcc and gnd pins two time in the code? one time should be enough.

**Comment by fkaup** [comment]
1. tested and works at least for the small OLED displays :)  - but I agree that it's not nice.. but allows to connect the display directly to the header instead of using wires. 
2. good spot. Had a merge conflict before and must have missed that.

**Comment by peterus** [comment]
@fkaup i removed your vcc and gnd pin approach as I personally don't like it. Of course you can use it in your branch. But I have the feeling that also some boards can be destroid with this.

**Comment by peterus** [comment]
@fkaup thanks for the new board :)

**Pull request merged**
