### PR TITLE
Add RAW APRS Output von Serial Port for later handling on Raspberry or PC

### PR DESCRIPTION
**Pull request by eaxi**
Good Morning everyone, my first Pullrequest, yeah.

So this addition should add a switch to activate the RAW-APRS-Message Output so that it is possible to process the Message over the Serial-Interface.

On Devices like the TTGO Beam, you don't have a LAN-Port, for Gateway usaged on high Builds with native Hamnet-Connection this is essential. Because, if you open a Wifi-Network on top of those buildings, the coverage is more then you won't. 

The Software for the RasPi to sent the DATA to the APRS is already in the making.

I'm open for any other Ideas, if the approach is wrong.

### CODE REVIEW

**Comment by SQ9MDD** [comment]
Is it possible to have the data sent to the port formatted as APRS TEXT?
This will allow to connect LORA DIGI to APRSIS32 application. All received data will be shown on the map

**Comment by eaxi** [comment]
@SQ9MDD Yes of course. That could be possible. I though of formatting it so that you could it to an TNC-Software'ish Gateway.

**Comment by SQ9MDD** [comment]
I made it quickly, and not very neatly, but it works very well

obraz

**Comment by eaxi** [comment]
Nice! Did you do it so that you only have this Output ? That'd be nice either.

**Comment by SQ9MDD** [comment]
Yes, but it was so quick I just turned off "logPrintD" and printed the frames generated by the digi and received by the radio to the serial. 
Basically, this would have to be done without harming the previous functions. 

Serial.println(BeaconMsg->encode());
Serial.println(msg->encode());

It would have to be done in such a way that turning this function on would turn off sending other data to the serial.

Ultimately the expected feature would be KISS TNC. A ready implementation is here:
https://github.com/markqvist/RNode_Firmware

But as for me it is too complicated to do it right.
I need someone with better "kung-fu" skills

**Comment by eaxi** [comment]
That's a good idea. I think it's easy to integrate with a lightweight switch in die config-file.

**Comment by eaxi** [comment]
So, how do we go further with this Idea?

@peterus  You've said it's an option that you implement such a function. Do you do it by yourself or should one of us make a new PR for develop-branch ?

**Comment by peterus** [comment]
please wait for some new implementations, i am working heavily on a new/complete redesigned version. this will take still some days.
To say the truth: i am not 100% convinced about connecting this firmware to an external software. We (german telegram chat) defined some very strickt rules for digipeating. this rules will be applied to a new project and the digi part in this igate software will be removed.
there are a lot of different possibilities to connect the esp32 to a wire if you ned: ([example](https://www.lora-aprs.info/docs/PoE-iGate/build/)
the goal of this project was to remove the need for a raspberry pi. there are other solutions if you want to run APRS via LoRa on a raspberry pi (simple PCB with a simple modem).

What do you think?

**Comment by SQ9MDD** [comment]
In my opinion. If we are talking about a radio network.
Right now, the most flexible way to build DIGI into a fixed network is with APRX software, which has the ability to arbitrarily filter traffic between radio interfaces. This allows you to regulate traffic between LORA 70cm and APRS 2m, at the DIGI level without having to open a connection through APRS-IS.
APRX needs a modem to work, for example KISS TNC via TCP or serial port.
KISS TNC functionality would solve this problem without burdening your software with additional algorithms.

If we are talking about temporary work in the field, you also need an interface for e.g. visualization of stations in the field. A great application is APRSIS32 for PC or APRSDROID for ANDROID.
KISS TNC is also a great interface here.

Working in the field with trackers capable of receiving frames is also interesting. It is very good that DIGI function exists now, because it increases the operating range of the network. In such cases sending to APRS-IS is only an addition, the most interesting is to play with the radio.

Sorry I can explain it better only in my own language.

**Comment by SQ9MDD** [comment]
> 
> 
> Nice! Did you do it so that you only have this Output ? That'd be nice either.

DIGI is up and running and data is flowing to APRSIS32...

obraz

**Comment by peterus** [comment]
@SQ9MDD sorry, but LoRa via APRS should never be mixed or feed from APRS on 2m!
the LoRa communication is way longer (in terms of seconds in the air) than 2m. LoRa is based on Long Range, and every Digi will decrease this range as the QRG is all the time full with messages which should not be on LoRa APRS.

I am in contact with the original authors from LoRa via APRS (some guys from Vienna und lower austria) and the original idea was this:
- send position reports/messages from a tracker via LoRa to some iGates in very good places.
- this iGates should forward the position reports/messages to an APRS-IS Server.
- from the APRS-IS server just Messages for trackers which are close to the iGate should be forwarded - nothing else as we want to keep the QRG free for the trackers.
- no other APRS formats are allowed than position reports, messages and in corner cases weather reports (max every 1, best every 3 hours).

you can see it is very strikt, and it should not be like on 2m where you can't even run a tracker in a city as there are high power digis all the time sending stupid stuff. Just image how it would be if you put some high power (1w) lora digis on some mountens in austria without limitation - you could never receive a tracker with low power because all the time the QRG will be blocked and the messages between the trackers would just be forwarded over all the alps all the time.

I am not completely against digis, please dont get me wrong. but there has to be some limitation and some restrictions. and i have a LOT of pressure form other people which are telling me how i should implement the digi firmware (some people are absolutly not happy that i am even considering something like this). Of course i cant control what you are doing at your house ;) but i just dont want to piss of a lot of people.

**Comment by SQ9MDD** [comment]
@peterus 
I understand what you mean but look more broadly. Lora can be a great extension for existing APRS 2m networks (LORA to 2m) . It's a shame to lose the potential to scrub LORA APRS just as a network feeding aprs.fi data.

Anyway, we'll see how these topics develop in the future.

R.

**Comment by peterus** [comment]
@SQ9MDD i totaly understand your point! sorry that my answer is currently not what you want to hear :D lets see how it woll continue in the future ;)

**Comment by eaxi** [comment]
So last word from me, i will close the PR and write a new one, when time for it has to come.

But i think both attempt are kinda right. I think some kinda "Rate-Limiting" is the way to go with such Digipeater. A break between the Bands is in my opinion a big mistake. But there should be a way to go between the both camps.

The way could be that the Firmware on the Devices only do Receiving and with additional Software it is possible turn the Device in to a Digipeater.

So, enough for that. Let us discuss in other Places. (New PR/Telegram or on a Mailinglist)

**Pull request closed without merging**
